### ISSUE TITLE
Remove the test texts from this readme file

### ISSUE THREAD

**Issue by SolidGray** [Vibro211/Vibro211#3]
It's not good idea to use this repository as repo for tests.
I would recommend to remove any text that is not intended to be displayed as your profile readme file.

Create the other repository for test/learning.

**Comment by Revax211** [comment]
Okily Dokily! If you have any ideas, you can always offer me anything to ding-dong-diddily-do here neighborino

**Comment by SolidGray** [comment]
Remove this demo text:
![image](https://user-images.githubusercontent.com/112625230/189334616-9f481ec2-764f-4cf0-85e7-4d95dc9eb83f.png)

It makes no sense to keep it here.

---

Remove, or fill the gaps in this list:
![image](https://user-images.githubusercontent.com/112625230/189334682-a2e80b87-fcc4-43c1-ab71-9b58c079283b.png)

**Comment by SolidGray** [comment]
Also create a repo for tests... with  ~~`test`~~ `github-tests` name, for example.

**Comment by SolidGray** [comment]
I have the better idea. Create a repo for python tasks.

`py-education`, for example.

**Comment by SolidGray** [comment]
I recommend to use lowercase [**kebab-case**](https://en.wikipedia.org/wiki/Letter_case#Kebab_case)d **repository** names.
